### ISSUE TITLE
Is this up to date and how run and view Wiki locally ?

### ISSUE THREAD

**Issue by tukangcode** [fmhy/FMHY#12]
Title.

**Comment by tukangcode** [comment]
Edit title : clone wiki but home.md are not connected to other part of wiki still show link to internet

**Comment by zinklog2** [comment]
Yeah it's updated almost daily. You can checkout [this repo](https://github.com/fmhy/FMHYedit) for daily commits.
As for running local, [Here's](https://raw.githubusercontent.com/nbats/FMHYedit/main/single-page) the entire wiki in markdown.
You can check other [Backups](https://www.reddit.com/r/FREEMEDIAHECKYEAH/wiki/backups/) to find the perfect way to browse.

**Comment by tukangcode** [comment]
thanks ! i close this issue
